services:
  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    image: service-registry:latest
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - app-network
    restart: unless-stopped

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: gateway:latest
    container_name: gateway
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - service-registry
    networks:
      - app-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: user-service:latest
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - service-registry
      - gateway
      - rabbitmq
    networks:
      - app-network
    restart: unless-stopped

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    image: notification-service:latest
    container_name: notification-service
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SMTP_USERNAME=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    depends_on:
      - service-registry
      - gateway
      - rabbitmq
    networks:
      - app-network
    restart: unless-stopped

  pet-service:
    build:
      context: ./pet-service
      dockerfile: Dockerfile
    image: pet-service:latest
    container_name: pet-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - service-registry
      - gateway
      - rabbitmq
    networks:
      - app-network
    restart: unless-stopped

  adoption-service:
    build:
      context: ./adoption-service
      dockerfile: Dockerfile
    image: adoption-service:latest
    container_name: adoption-service
    ports:
      - "8086:8086"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - service-registry
      - gateway
      - rabbitmq
    networks:
      - app-network
    restart: no


networks:
  app-network:
    driver: bridge
