name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up JDK 21
      - name: Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Cache Maven dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Install Maven (if not pre-installed)
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      # 5. Build and Test Service Registry
      - name: Build and Test Service Registry
        working-directory: ./service-registry
        run: |
          mvn clean verify

      # 6. Lint Service Registry
      - name: Lint Service Registry
        working-directory: ./service-registry
        run: |
          mvn checkstyle:check

      # 7. Build and Test User Service
      - name: Build and Test User Service
        working-directory: ./user-service
        run: |
          mvn clean verify -Dspring.profiles.active=test

      # 8. Lint User Service
      - name: Lint User Service
        working-directory: ./user-service
        run: |
          mvn checkstyle:check
